name: Curl Bank Jatim
on: 
  push:
    branches:
      - main
    paths:
      - bank-jatim.sh
  schedule:
    - cron: '0 0,9 * * *'  # Menjalankan 2 kali sehari pada pukul 00:00 UTC|07.00 WIB dan 09:00 UTC|16.00 WIB (00:00 dan 09:00 UTC)
  workflow_dispatch:

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Running Curl Request Bank Jatim
      env:
        CLOUDLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CLOUDFLARE_KV_ID: ${{ secrets.CF_KV_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # Ambil token dari GitHub Secrets
      run: |
        chmod +x ./bank-jatim.sh # Pastikan file memiliki permission execute
        ./bank-jatim.sh
